/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xYHqD5MkVkT
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "./ui/theme-toggle";

function NavLink({ href, children }) {
    return (
        <Link className="hover:underline" href={href}>
            {children}
        </Link>
    );
}

export function Navbar() {
    return (
        <nav className="fixed inset-x-0 top-0 z-50 bg-white shadow-sm dark:bg-gray-950/90">
            <div className="w-full max-w-7xl mx-auto px-4">
                <div className="flex justify-between h-14 items-center">
                    <Link className="flex items-center" href="/">
                        <MountainIcon className="h-6 w-6" />
                        <span className="sr-only">Plants fetcher</span>
                    </Link>

                    <div className="flex gap-2 mx-auto px-3">
                        <NavLink href="/plants">Plants</NavLink>
                    </div>

                    <ThemeToggle />
                </div>
            </div>
        </nav>
    );
}

function MountainIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
        </svg>
    );
}
